### ISSUE TITLE
Create from template can throw an error

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1005]
Using the `nodejs-mongodb.json` template & pasting it in the `Import YAML / JSON` field, I get a console error w/o any feedback on the page:

![screen shot 2016-12-07 at 5 07 33 pm](https://cloud.githubusercontent.com/assets/280512/20988710/e39cd57e-bc9f-11e6-9b9e-8afcc3073a3e.png)

@jwforres @spadgett

**Comment by jwforres** [comment]
Are any templates working, is this because something changed with createFromTemplateURL in the run on openshift stuff

**Comment by benjaminapetersen** [comment]
@rhamilto thoughts on this?  I don't recall working on the `createFromTemplateURL` function.

**Comment by rhamilto** [comment]
D'oh.  We broke the createFromTemplateURL filter (and maybe createFromImageURL filter, too).  Need to fix tomorrow.

**Comment by benjaminapetersen** [comment]
Oop!
So the `nodejs-mongodb.json` template would not work, assuming no templates will.  However, creating other objects seems to be fine. For example, this worked:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.type
  restartPolicy: Never
```
