### ISSUE TITLE
Console say dc change saved but on review no change was saved

### ISSUE THREAD

**Issue by magick93** [openshift/origin-web-console#1221]
OpenShift Master: v1.4.1+3f9807a
Kubernetes Master: v1.4.0+776c994

In an attempt to workaround https://github.com/fabric8io/jenkins-docker/issues/110 we try to edit Jenkins Deployment Config in the OpenShift console. 
We navigate to `Deployments  >  jenkins,` then click `Actions > Edit YAML,` change:

```
      serviceAccountName: jenkins
      serviceAccount: jenkins
      securityContext: {}
```

to (as described on https://kubernetes.io/docs/user-guide/security-context/)

```
      serviceAccountName: jenkins
      serviceAccount: jenkins
      securityContext:
        privileged: true
```

then save, and see
![selection_667](https://cloud.githubusercontent.com/assets/2173213/22647068/b80a22ae-ec6f-11e6-85a3-6fccf016cb3c.png)

Yet when we again click on Actions > Edit YAML, the change we added is gone.

Additional
When I try this in vim I get the same result. The change is not saved. But no indication of error.
```
$ oc edit dc jenkins
deploymentconfig "jenkins" skipped
```

**Comment by spadgett** [comment]
It looks like you're changing the pod security context, which doesn't have a `privileged` field. The container security context does. Currently, OpenShift ignores unrecognized fields when editing YAML, so there is no error when you save (and why you see the skipped message when using the CLI).

Can you try changing this one instead and see if it works?

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/22648364/530d67ce-ec44-11e6-90a4-145233224d08.png)

**Comment by spadgett** [comment]
@jwforres We might be able to warn about this case. If the resource version in the PUT response body is the same as before, no changes were applied. @liggitt can you confirm?

**Comment by magick93** [comment]
Im trying to change the security context for the containers, as described on https://kubernetes.io/docs/user-guide/security-context/

```
    spec:
      containers:
        - name: fabric8-container
          image: 'fabric8/fabric8-console:2.2.199'
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: OAUTH_AUTHORIZE_URI
              valueFrom:
                configMapKeyRef:
                  name: fabric8
                  key: oauth-authorize-uri
            - name: GITHUB_OAUTH_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: fabric8
                  key: github-oauth-client-secret
            - name: GITHUB_OAUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: fabric8
                  key: github-oauth-client-id
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OAUTH_CLIENT_ID
              value: fabric8
            - name: OAUTH_PROVIDER
              value: openshift
            - name: FABRIC8_FABRIC8_CONFIGMAP
              value: >-
                auth-mode=basic;github-oauth-client-id=${GITHUB_OAUTH_CLIENT_ID};github-oauth-client-secret=${GITHUB_OAUTH_CLIENT_SECRET};master-uri=k8s;oauth-authorize-uri=https://openshift.hughestech.co:8443/oauth/authorize
          resources:
            limits:
              cpu: '0'
              memory: '0'
            requests:
              cpu: '0'
              memory: '0'
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
```

In my case there is no predefined `privileged: false` setting.

![selection_668](https://cloud.githubusercontent.com/assets/2173213/22648822/8f61414e-ec78-11e6-8668-a919f2b5a030.png)
