### ISSUE TITLE
Image ID not displayed correctly for some images

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1264]
![screen_shot_2017-02-20_at_9_39_59_am](https://cloud.githubusercontent.com/assets/1167259/23129429/a60b3b38-f750-11e6-9d29-67daab50449f.png)

```yaml
      image: 'openshift/origin-metrics-heapster:v1.4.1'
      imageID: >-
        docker-pullable://docker.io/openshift/origin-metrics-heapster@sha256:30a2fa7376e67ce6001ae65c29137b09696a3c00b3457c207115ea9bab607018
```

@jwforres fyi
