### ISSUE TITLE
Build page should show Git revision when available

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1669]
Builds have a `spec.revision` we can show on the browse build page.

```yaml
spec:
  revision:
    git:
      author:
        email: bparees@users.noreply.github.com
        name: Ben Parees
      commit: 3d44de3ba8fef0b2baca4ddd001c0db286ea4cd3
      committer:
        email: noreply@github.com
        name: GitHub
      message: 'Merge pull request #117 from openshift/revert-112-revert-111-nodejs6'
```

@smarterclayton @jwforres
