### ISSUE TITLE
Failed builds not showing up in build timing table

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#1851]
See:

![screenshot from 2017-07-14 10-36-37](https://user-images.githubusercontent.com/7328370/28223468-617a613c-6880-11e7-9288-5248a398a5d1.png)

**Comment by stevekuznetsov** [comment]
Server version: openshift v3.6.0-alpha.0+8125090-206

**Comment by spadgett** [comment]
The builds missing from the chart don't have a `status.duration` or a `status.completionTimestamp`. The duration in the table is the time from build start to the current time, which is not accurate.

@bparees

**Comment by bparees** [comment]
pretty sure this was broken back then.  alpha.0 is old.  how about rc.0?

```
 status:
    completionTimestamp: 2017-07-14T19:12:33Z
    config:
      kind: BuildConfig
      name: ruby-sample-build
      namespace: p1
    duration: 19000000000
    message: Failed to fetch the input source.
    output: {}
    outputDockerImageReference: 172.30.144.43:5000/p1/origin-ruby-sample:latest
    phase: Failed

```
