### ISSUE TITLE
Support for chained or pipelined builds

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#2008]
#It is common for us to use multi-stage builds for generating incremental images and being more efficient in our build and release pipelines. Today, navigating to the builds overview does not show us any of the relationships between build inputs and outputs. It would be awesome if a relationship where builds or build configurations are pipelined would be exposed in the UI.

Example:

<details>
<summary><code>buildconfig/oauth-proxy-binary</code></summary>

```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  name: oauth-proxy-binary
spec:
  failedBuildsHistoryLimit: 2
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: oauth-proxy:binaries
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM openshift/origin-release:golang-1.7
      COPY . /go/src/github.com/openshift/oauth-proxy
      RUN cd /go/src/github.com/openshift/oauth-proxy && \
          CGO_ENABLED=0 go build -a -tags netgo .
    git:
      uri: https://github.com/openshift/oauth-proxy.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: openshift/origin-release:golang-1.7
      imageOptimizationPolicy: SkipLayers
    type: Docker
  successfulBuildsHistoryLimit: 1
  triggers:
  - type: ConfigChange
  - github:
      secret: xxxx
    type: GitHub
```

</details>

<details>
<summary><code>buildconfig/oauth-proxy</code></summary>

```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  name: oauth-proxy
spec:
  failedBuildsHistoryLimit: 2
  nodeSelector: null
  output:
    pushSecret:
      name: registry-push
    to:
      kind: DockerImage
      name: docker.io/openshift/oauth-proxy:v1.0.0
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM        centos:7
      MAINTAINER  Clayton Coleman <ccoleman@redhat.com>

      COPY oauth-proxy /bin/oauth-proxy

      ENTRYPOINT [ "/bin/oauth-proxy" ]
    images:
    - from:
        kind: ImageStreamTag
        name: oauth-proxy:binaries
      paths:
      - destinationDir: .
        sourcePath: /go/src/github.com/openshift/oauth-proxy/.
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7
      imageOptimizationPolicy: SkipLayers
    type: Docker
  successfulBuildsHistoryLimit: 1
  triggers:
  - imageChange:
      from:
        kind: ImageStreamTag
        name: oauth-proxy:binaries
    type: ImageChange
```

</details>

As you can see, the `.spec.output.to.kind` and `.spec.output.to.name` on the `oauth-proxy-binaries` config match `.spec.source.images[0].from` fields in the `oauth-proxy` config. It could also match `.spec.strategy.dockerStrategy.from` fields if it were chained differently.

/cc @spadgett @smarterclayton
