### ISSUE TITLE
Console loops endlessly when it can't connect to API server

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2758]
Since we proxy from the master to the console, this should rarely happen. If the console can't connect to the API server, however, it goes into a loop trying to do API discovery. This could happen because of a misconfiguration of `clusterInfo.masterPublicURL` or possibly due to incorrect certs.

/assign
/kind bug
/priority p2

@jwforres FYI

**Comment by dtaylor113** [comment]
+1 for incorrect certs.  When this happens to me I end up clearing my brower cache/cookies/certs and it fixes the issue.

**Comment by jwforres** [comment]
I think this typically happens when you already have a user token in local storage but the cert for the api server changes. If you don't have a token you get sent to login flow which triggers cert acceptance.

**Comment by jwforres** [comment]
So what is supposed to happen if you have the token already but API requests fail, it's supposed to go to an error page with a link to check your server connection.

**Comment by spadgett** [comment]
Here's what I'm seeing:

![screencast 2018-02-02 14-33-15](https://user-images.githubusercontent.com/1167259/35755802-babab94e-0836-11e8-9c87-952931f135f6.gif)

**Comment by jwforres** [comment]
We definitely shouldn't redirect to the error page if we are already on it. Ideally we wouldn't even try to do discovery if we are on it.

**Comment by cmoulliard** [comment]
I still experiment the infinite loop after changing :  

- corsAllowOrigins (modified within master-config.yaml file)

```
vi /var/lib/minishift/openshift.local.config/master/master-config.yaml
corsAllowedOrigins:
- //admin-openshift-web-console\.192\.168\.65\.5\.nip\.io(:|\z)
- //127\.0\.0\.1(:|$)
- //192\.168\.65\.5:8443$
- //localhost(:|$)
docker restart origin
```
- ConfigMap of the openshift-web-console

```
oc get configmap/webconsole-config -o yaml
apiVersion: v1
data:
  webconsole-config.yaml: |
    apiVersion: webconsole.config.openshift.io/v1
    clusterInfo:
      consolePublicURL: https://admin-openshift-web-console.192.168.65.5.nip.io/console/
      loggingPublicURL: ""
      logoutPublicURL: ""
      masterPublicURL: https://admin-openshift-web-console.192.168.65.5.nip.io
      metricsPublicURL: ""
```
