### ISSUE TITLE
Membership page should honor role binding restrictions

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2773]
Right now we don't look at role binding restrictions in our edit membership page. This will result in 403 forbidden responses from the API server. We should investigate if there is something better we can do in the UI.

@jwforres @benjaminapetersen 

/area usability
/priority p2

**Comment by benjaminapetersen** [comment]
Not sure I'm familiar with  role binding restrictions but I can do some homework

**Comment by benjaminapetersen** [comment]
Sounds like this might be enough work to be a Trello.

**Comment by enj** [comment]
I am not sure this can be built into the web console without duplicating most of the logic in the admission plugin.  You also run into the issue of drifting from the server over time.   On a related note, do you guys hide the membership page if the user cannot edit role bindings?  They could still have indirect access via a SA, but that is probably not important for the console.

**Comment by jwforres** [comment]
I don't think we should duplicate all the logic, I think there are certain situations we could look for. If there is a restriction on users that only the current user is allowed, why show them the ability to add users?

I don't remember if we check list or create on rolebinding, but only project admins see the membership page with the OOTB roles.

**Comment by enj** [comment]
Here are the RBR that online uses in each namespace (see inline comments):

```yaml
kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    name: match-own-service-account-group  # Allows creating role bindings that target all SAs in the given namespace
  spec:
    grouprestriction:
      groups:
      - system:serviceaccounts:{NAMESPACE}
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    name: match-own-service-accounts  # Allows creating role bindings that target any SA in the given namespace
  spec:
    serviceaccountrestriction:
      namespaces:
      - {NAMESPACE}
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    name: match-project-admin-user  # Allows creating role bindings that target the given user
  spec:
    userrestriction:
      users:
      - {USER}
```

The logic for when the RBR admission plugin is enabled is:

1. Someone tries to create a role binding
2. We iterate over all RBR
3. If any of the RBR allow the role binding, short circuit and ALLOW
4. Default to DISALLOWED

That is basically the entire logic of the admission plugin.  I see no way to answer:

> If there is a restriction on users that only the current user is allowed, why show them the ability to add users?

without copying that logic.
