### ISSUE TITLE
field display_type property "textarea" being shown as regular input field in update view

### ISSUE THREAD

**Issue by odra** [openshift/origin-web-console#2985]
Hello,

I have defined the following parameter in my apb plan:

```yaml
-
  name: ANDROID_SDK_CONFIG
  type: string
  display_type: textarea
  description: "Android SDK config in INI format"
  title: Android SDK config
  required: False
  updatable: True
```

The field is shown as a textarea html field when provisioning a new service but it is shown as a regular input html field when I click on the "edit" button in the service details:

![screenshot from 2018-05-01 12-29-04](https://user-images.githubusercontent.com/2183506/39479347-5bb90154-4d3b-11e8-8986-a804482dfb02.png)

Is this the correct repository to open issue? or should I raise it in origin-web-catalog?
