### ISSUE TITLE
Trying to navigate to https://<cluster_public_ip>:8443 redirects to https://127.0.0.1:8443/console/

### ISSUE THREAD

**Issue by djwhatle** [openshift/origin-web-console#3072]
## **Issue Description**
I'm using `oc cluster up` v3.11 via catasb to bring up a web console, and I've found that:

**_Navigating to_:**
`https://<cluster_public_ip>:8443` 
**_Redirects to_:**  
`https://127.0.0.1:8443/console/`
**_Instead of the expected:_**
`https://<cluster_public_ip>:8443/console` 

Which I can't load since I'm not running the cluster on my localhost.

--- 
**_If I instead navigate directly to:_**
`https://<cluster_public_ip>:8443/console`

I get a nice web console that looks like this:
![image](https://user-images.githubusercontent.com/7576968/45236691-93e14a80-b2aa-11e8-986e-c2e72ec57efe.png)

## **oc version output**
oc v3.11.0-alpha.0+1ff2229-9
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://<cluster_public_ip>:8443
kubernetes v1.11.0+d4cacc0

## Web Console Configmap (shown in YAML for readability)
```yaml
---
apiVersion: v1
data:
  webconsole-config.yaml: |
kind: WebConsoleConfiguration
apiVersion: webconsole.config.openshift.io/v1
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: "/var/serving-cert/tls.crt"
  keyFile: "/var/serving-cert/tls.key"
  clientCA: ''
  namedCertificates: 
  maxRequestsInFlight: 0
  requestTimeoutSeconds: 0
clusterInfo:
  consolePublicURL: https://<cluster_public_ip>:8443/console/
  masterPublicURL: https://<cluster_public_ip>:8443
  loggingPublicURL: ''
  metricsPublicURL: ''
  logoutPublicURL: ''
  adminConsolePublicURL: ''
features:
  inactivityTimeoutMinutes: 0
  clusterResourceOverridesEnabled: false
extensions:
  scriptURLs: []
  stylesheetURLs: []
  properties: 
kind: ConfigMap
metadata:
  name: webconsole-config
  namespace: openshift-web-console
  selfLink: /api/v1/namespaces/openshift-web-console/configmaps/webconsole-config

```
