### ISSUE TITLE
Make logging URL query customizable

### ISSUE THREAD

**Issue by jeffspahr** [openshift/origin-web-console#3092]
The web console configmap lets the OpenShift admin change the logging URL that end users see with the View Archive link for pod logs via the loggingPublicURL field.

```
webconsole-config.yaml:
----
apiVersion: webconsole.config.openshift.io/v1
clusterInfo:
  consolePublicURL: https://master2.example.com:8443/console/
  loggingPublicURL: https://kibana.apps2.example.com
  logoutPublicURL: ''
  masterPublicURL: https://master2.example.com:8443
  metricsPublicURL: https://hawkular-metrics.apps2.example.com/hawkular/metrics
  adminConsolePublicURL: https://console.apps2.example.com/
```

This will use the following query from https://github.com/openshift/origin-web-console/blob/master/app/scripts/services/logLinks.js
```
      var template = _.template([
        "<%= baseURL %>#/discover?",
        "_g=(",
          "time:(",
            "from:now-1w,",
            "mode:relative,",
            "to:now",
          ")",
        ")",
        "&_a=(",
          //"columns:!(_source),",
          "columns:!(kubernetes.container_name,message),",
          "index:'<%= index %>',",
          "query:(",
            "query_string:(",
              "analyze_wildcard:!t,",
              "query:'kubernetes.pod_name:\"<%= podname %>\" AND kubernetes.namespace_name:\"<%= namespace %>\"'",
            ")",
          "),",
          "sort:!('@timestamp',desc)",
        ")",
        // NOTE: slightly older versions of kibana require openshift_ prefix, not console_
        "#console_container_name=<%= containername %>",
        // backlink should be encoded.  passing URI.encode(backlink) should be sufficient
        "&console_back_url=<%= backlink %>"
      ].join(''));
```

In our case we're still using Kibana, but we are shipping logs with filebeat so the field names are different:
kubernetes.pod.name instead of kubernetes.pod_name
kubernetes.namespace instead of kubernetes.namespace_name

There could be other use cases where people aren't using Kibana at all so an entirely different query format may be appropriate.

Would it be reasonable to move that configuration to a configmap?
