### ISSUE TITLE
Pod env variables from a config map not showing up on pod page

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#862]
@jwforres @benjaminapetersen 

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/20222438/54d91a7e-a803-11e6-9ef7-e0ef47cdef0b.png)

```yaml
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.type
```
